version: '3'
services:
  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Admin
      - MONGO_INITDB_ROOT_PASSWORD=myNewPassword

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=Admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=myNewPassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb